---
driver_plugin: joyent
driver_config:
  joyent_username: "<%= ENV['SDC_ACCOUNT'] %>"
  joyent_keyfile: "<%= ENV['HOME'] %>/.ssh/id_rsa"
  joyent_keyname: "<%= ENV['SDC_KEY_ID'] %>"
  joyent_url: "<%= ENV['SDC_URL'] %>"
  joyent_flavor_id:  t4-standard-2G

platforms:
- name: centos-6-20150618-smartmachine
  driver_config:
    joyent_image_id: aa11a466-15c4-11e5-add5-0700f90a1098

- name: debian-7-20150618-smartmachine
  driver_config:
    joyent_image_id: 1187b54a-15ca-11e5-a80c-275e2f64f91e

- name: ubuntu-14.04-20150618-smartmachine
  driver_config:
    joyent_image_id: 5a0145ee-15c4-11e5-9c49-ef53e8760a7e

# this KVM image added as a reference
- name: ubuntu-14.04-20150225.2-virtualmachine
  driver_config:
    joyent_image_id: c864f104-624c-43d2-835e-b49a39709b6b
    username: ubuntu

suites:
  - name: default
