---
driver_plugin: joyent
driver_config:
  joyent_username: yetu_testing
  joyent_keyfile: ./id_rsa
  joyent_keyname: travis_ci
  joyent_url: https://us-east-3.api.joyent.com
  joyent_flavor_id: g3-devtier-0.25-smartos
  username: root

platforms:
- name: lx-ubuntu-14.04_20150601
  driver_config:
    joyent_image_id: a21a64a0-0809-11e5-a64f-ff80e8e8086f

suites:
  - name: default
