---
driver:
  name: vagrant

provisioner:
  name: shell
  script: test/templates/bootstrap.sh

platforms:
- name: lx
  driver_config:
    box: livinginthepast/smartos
    box_url: https://atlas.hashicorp.com/livinginthepast/boxes/smartos
    vagrantfile_erb: test/templates/Vagrantfile.smartos.erb
    zone:
      name: lx_zone
      brand: lx
      image: 14a960b0-614e-11e4-a095-eb789315ae39

suites:
  - name: default
