---
driver:
  name: vagrant

provisioner:
  name: shell
  script: test/templates/bootstrap.sh

platforms:
- name: lx
  driver_config:
    box: livinginthepast/smartos
    box_url: https://atlas.hashicorp.com/livinginthepast/boxes/smartos
    vagrantfile_erb: test/templates/Vagrantfile.smartos.erb
    zone:
      name: lx_zone
      brand: lx
      image: 818cc79e-ceb3-11e4-99ee-7bc8c674e754

suites:
  - name: default
