language: ruby
rvm:
- 2.2.1
before_install:
- openssl aes-256-cbc -K $encrypted_5f6186889f46_key -iv $encrypted_5f6186889f46_iv
  -in id_rsa.enc -out id_rsa -d
bundler_args: "--deployment --binstubs"
script:
- "./bin/kitchen test --destroy=always"
