language: ruby
rvm:
  - 2.2.1
before_install:
  - sudo echo deb http://download.virtualbox.org/virtualbox/debian trusty contrib >> /etc/apt/sources.list
  - wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq virtualbox vagrant
sudo: required
dist: trusty
script:
  - bundle install
  - kitchen test --destroy=always
